services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./:/app

  demo:
    build:
      context: .
      dockerfile: docker/Dockerfile.demo
    env_file:
      - .env
    ports:
      - "8501:8501"
    volumes:
      - ./:/app
